### ISSUE TITLE
Cannot upload .html files

### ISSUE THREAD

**Issue by fafan999** [paulober/Pico-W-Go#61]
## What are the steps to reproduce this issue?
1. Start to work on a .html file.
2. Click all commands

## What happens?
"Upload current file" command doesn't pop up in the available commands.

## What were you expecting to happen?
I was expecting this command so I can read this .html file in my main.py script.

## Any logs, error output, etc?
-

## Any other comments?
-

## Support info
-

**Comment by paulober** [comment]
That because this command only gets enabled for python  (.py) files. I'll remove this constraint in the next hotfix so you can upload it with the upload command like before.
I the mean time you can mount the new virtual workspace and transfer the file by draging it onto the Pico or by creating a file there and copy pasting the content.
