### ISSUE TITLE
Link to rp2-pico-w-20230407-unstable-v1.19.1-1009-gcfd3b7093.uf2 broken in README.md

### ISSUE THREAD

**Issue by arudnitsky** [paulober/Pico-W-Go#77]
## What are the steps to reproduce this issue?
1. Click on the link to the [rp2-pico-w-20230407-unstable-v1.19.1-1009-gcfd3b7093.uf2](https://micropython.org/resources/firmware/rp2-pico-w-20230407-unstable-v1.19.1-1009-gcfd3b7093.uf2) firmware.

## What happens?
<img width="257" alt="image" src="https://user-images.githubusercontent.com/2124863/233805628-6a2e598e-e1ff-43ea-a6f7-87cf10947018.png">

## Any other comments?
(I opened this as an issue since there is no Discussions area.)
That version of the firmware is no longer available to download. The oldest nightly available from 2023-04-14, and I am unable to find the specified version of the firmware on the MicroPython site.

Is it possible to still download that build from somewhere? Alternatively, what's the recommendation for which version of firmware to use? I can't find any further information about this.

**Comment by paulober** [comment]
@arudnitsky The firmware linked in the README is for people to know on which version the auto-completion is based on. So if an API change is implemented with a newer version its currently not available in the extension until the stubs here are updated.

But you can still use any newer firmware with it. Also the reason why the link wasn't available anymore is because the unstable versions changed so frequently so they remove older version very fast from their servers.
